Add support to change the current CulutureInfo
Biarity/Sieve pull request #187
Opened 2023-02-14 14:01 UTC by spinbase

When the value of a filter like "MeanRating==1.2" is parsed/converted and the current CultureInfo is e.g. de-DE, then the conversion fails with an exception, because 1.2 is not a valid format in culture.

So it would be good, to let the developer decide which CultureInfo should be used by Sieve.

Therefore this pull request added a CultureInfo property to the SieveOptions, that is used in the Apply method of the SieveProcessor to change the current culture during processing.

2023-02-23 02:04 UTC, hasanmanzak requested changes
I'm sorry but I can not approve this, at least as-is. CultureInfo manupulation is risky and very open-ended. One can ask for value encapsulation like `filters=field==((en-en)data), field2!=currentCulturedData`, or full query encapsulation like `filters=field==data, field2!=data2&culture=en-en` or a global sieve startup parameter. We should consider this widely and then we should implement such support.

By the way, there is a PR (#79) opened about almost 4 years ago. We did resolved the conflicts with another one (#125) and asked for some unit tests. Maybe you can keep on going on that path? What'd you say? 😄

2023-02-23 02:04 UTC, hasanmanzak commented on Sieve/Models/SieveOptions.cs
> +        public CultureInfo CultureInfo { get; set; } = CultureInfo.CurrentCulture;
It's better to have this setting to be a string which can be read from `appsettings.json`.

2023-02-23 02:04 UTC, hasanmanzak commented on Sieve/Services/SieveProcessor.cs
> +            CultureInfo.CurrentCulture = Options.Value.CultureInfo;
Errm, no, please.. You should not alter the current culture!..

2023-07-26 07:06 UTC, spinbase commented on Sieve/Models/SieveOptions.cs
> +        public CultureInfo CultureInfo { get; set; } = CultureInfo.CurrentCulture;
You are right. Fixed it with solution from https://github.com/Biarity/Sieve/pull/125

2023-07-26 07:07 UTC, spinbase commented on Sieve/Services/SieveProcessor.cs
> +            CultureInfo.CurrentCulture = Options.Value.CultureInfo;
You're right. Really bad :-) Also fixed with solution from https://github.com/Biarity/Sieve/pull/125

2023-07-26 07:09 UTC, spinbase commented
> I'm sorry but I can not approve this, at least as-is. CultureInfo manupulation is risky and very open-ended. One can ask for value encapsulation like `filters=field==((en-en)data), field2!=currentCulturedData`, or full query encapsulation like `filters=field==data, field2!=data2&culture=en-en` or a global sieve startup parameter. We should consider this widely and then we should implement such support.
> 
> By the way, there is a PR (#79) opened about almost 4 years ago. We did resolved the conflicts with another one (#125) and asked for some unit tests. Maybe you can keep on going on that path? What'd you say? 😄

Hi, I did what you proposed. So now this PR includes the solution from https://github.com/Biarity/Sieve/pull/125 extended with test cases

2023-11-11 15:58 UTC, closed without merging